### ISSUE TITLE
snippets not showing when calling show available snippets (alt-shift-s | :command:-shift-s)

### ISSUE THREAD

**Issue by jeroldhaas** [manolenso/atom-gulp-snippets#4]
(alt-shift-s | cmd-shift-s) doesn't show any of the available snippets in the snippet list.

**Comment by manolenso** [comment]
Unexpectedly the last update 1.0.10  break the snippets package!
so reinstall them: apm install gulp-snippets 
reload Atom 
type 'gu' and you should see 
![gulp](https://cloud.githubusercontent.com/assets/3215438/9641974/e3ff7546-51b9-11e5-9cda-5c7f75905f71.png)

**Comment by jeroldhaas** [comment]
Working again! Thanks! :smile:

On 02/09/2015, Laurent Rémy notifications@github.com wrote:

> Unexpectedly the last update 1.0.10  break the snippets package!
> so reinstall them: apm install gulp-snippets
> reload Atom
> type 'gu' and you should see
> ![gulp](https://cloud.githubusercontent.com/assets/3215438/9641974/e3ff7546-51b9-11e5-9cda-5c7f75905f71.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/manolenso/atom-gulp-snippets/issues/4#issuecomment-137221445

## 

Cheers,
Jerold Haas

_Software Developer_
ASP.NET
ASP.NET MVC
C#, F#, .NET
PHP 4/5
JavaScript (jQuery, Mootools)
Flash / Flex 3 & 4 / ActionScript 2 & 3
MSSQL, MySQL, PostgreSQL
XHTML 1.0, HTML5, CSS2, CSS3

http://www.twitter.com/jeroldhaas
http://www.linkedin.com/in/jchaas
http://jhaas.emurse.com/
